const SUCCESS = 200
const CREATED = 201
const NO_CONTENT = 202
const BAD_REQUST = 400
const UNAUTHORIZED = 401
const FORBIDDEN = 403 // it does not have access permission
const PAGE_NOT_FOUND = 404
const INTERNAL_SERVER_ERROR = 500
const SERVICE_NOT_AVAILABLE = 503
const PAYMENT_GATEWAY_TIMEOUT = 504
const INVALID_TOKEN = 498 //invalid or expire token
const EMPTY_TOKEN = 499 //token is required
const PRECONDITION_FAILED = 412
const CONFLICT_STATUS = 409



module.exports = { SUCCESS, CREATED, NO_CONTENT, BAD_REQUST, UNAUTHORIZED, FORBIDDEN, PAGE_NOT_FOUND, INTERNAL_SERVER_ERROR, SERVICE_NOT_AVAILABLE, PAYMENT_GATEWAY_TIMEOUT, INVALID_TOKEN, EMPTY_TOKEN, PRECONDITION_FAILED, CONFLICT_STATUS }